#ifndef MAINHELPER_H
#define MAINHELPER_H

#include "Globals.h"

/**		Global main variables	**/
// Analysis variables
int method, blur, blurAmt, morphAmt, shadowThr, detect;

// Current image frame
cv::Mat currFrame;

// Foreground mask generated by background subtraction
cv::Mat fgMask;

// MOG2 background subtractor
cv::Ptr<cv::BackgroundSubtractor> pMOG2;
cv::Ptr<cv::BackgroundSubtractor> pKNN;

// Keyboard input
int keyboard;
/**	*	*	*	*	*	*	*	**/

void processInput(int argc, char* argv[]);

void processVideo(char* argv[]);

void processVideoSubtr(char* videoFilename);
void processVideoOF(char* videoFilename);

//void processImages(char* firstFrameFilename);
#endif
