#ifndef MAINHELPER_H
#define MAINHELPER_H

#include "Globals.h"

/**		Global main variables	**/
// Analysis variables
int method, blur, blurAmt, morphAmt, shadowThr;

// Current image frame
cv::Mat currFrame;

// Foreground mask generated by MOG2 method
cv::Mat fgMaskMOG2;
cv::Mat fgMaskKNN;

// MOG2 background subtractor
cv::Ptr<cv::BackgroundSubtractor> pMOG2;
cv::Ptr<cv::BackgroundSubtractor> pKNN;

// Keyboard input
int keyboard;
/**	*	*	*	*	*	*	*	**/

void processVideoMOG(char* videoFilename);
void processVideoKNN(char* videoFilename);

//void processImages(char* firstFrameFilename);
#endif
